// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wuvjajjvnozaxlgegkrd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1dmphamp2bm96YXhsZ2Vna3JkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0ODUzNzIsImV4cCI6MjA3MzA2MTM3Mn0.wPdcuuXihT3VQDMXP4qNpe1KW774zdazA_5-NNmkCP8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});